[package]
name = "jfc"
version = "0.1.0"
edition = "2021"


[lints.rust]
unsafe_code = "forbid"

[dependencies]
clap = { version = "4.5", features = ["cargo"] }
toy-json-formatter = { path = "../json/" }
